# Generated by Django 3.2.19 on 2023-07-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organziation',
            new_name='Organization',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='organziation',
            new_name='organization',
        ),
    ]
