# Generated by Django 3.2.19 on 2023-07-04 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('reason', models.CharField(blank=True, choices=[('SICK', 'Sick'), ('ANNUAL', 'Annual'), ('OTHER', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('REVIEW', 'Review'), ('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=50)),
                ('leave_detail', models.TextField(blank=True, max_length=1000)),
                ('leave_type', models.CharField(choices=[('LEAVE', 'Leave'), ('WFH', 'Wfh')], max_length=50)),
                ('type_of_request', models.CharField(choices=[('FULL DAY', 'Full Day'), ('HALF DAY', 'Half Day')], max_length=50)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=120)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=50)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
