# Generated by Django 3.2.19 on 2023-07-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('reason', models.CharField(blank=True, choices=[('SICK', 'Sick'), ('ANNUAL', 'Annual'), ('OTHER', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('REVIEW', 'Review'), ('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=50)),
                ('leave_detail', models.TextField(blank=True, max_length=1000)),
                ('leave_type', models.CharField(choices=[('LEAVE', 'Leave'), ('WFH', 'Wfh')], max_length=50)),
                ('type_of_request', models.CharField(choices=[('FULL DAY', 'Full Day'), ('HALF DAY', 'Half Day')], max_length=50)),
                ('comment', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
