# Generated by Django 3.2.19 on 2023-07-06 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Approve', 'Approve'), ('Reject', 'Reject')], max_length=50)),
                ('comment', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, choices=[('Sick', 'Sick'), ('Annual', 'Annual'), ('Other', 'Other')], max_length=50)),
                ('leave_detail', models.TextField(blank=True, max_length=1000)),
                ('leave_type', models.CharField(choices=[('Leave', 'Leave'), ('Wfh', 'Wfh')], max_length=50)),
                ('type_of_request', models.CharField(choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day')], max_length=50)),
                ('status', models.CharField(choices=[('Review', 'Review'), ('Approve', 'Approve'), ('Reject', 'Reject')], max_length=50)),
                ('comment', models.TextField()),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL)),
                ('approve_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approve_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
