# Generated by Django 3.2.19 on 2023-07-17 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaveform', '0006_timelogactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelogactivity',
            name='timelog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaveform.timelog'),
        ),
    ]
