# Generated by Django 3.2.19 on 2023-07-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaveform', '0007_timelogactivity_timelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveform',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='comment',
        ),
    ]
