# Generated by Django 3.2.19 on 2023-08-07 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaveform', '0010_alter_comment_comment_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveform',
            name='Jsonfield',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commentfile',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaveform.comment', verbose_name='Email'),
        ),
    ]
