# Generated by Django 3.2.19 on 2023-08-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaveform', '0011_auto_20230807_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveform',
            name='Jsonfield',
        ),
    ]
